import { test, expect } from '@playwright/test'

test('register, verify, trade, receive notification, export and sign out', async ({page}) => {
  const identity=`qa${Date.now()}`
  await page.goto('/')
  await page.getByRole('button',{name:'Portfolio & risk',exact:true}).click()
  await page.getByRole('button',{name:'Create account',exact:true}).click()
  await page.getByLabel('Username',{exact:true}).fill(identity)
  await page.getByLabel('Email',{exact:true}).fill(`${identity}@example.com`)
  await page.getByLabel('Password',{exact:true}).fill('QA-only-password-123!')
  await page.getByRole('button',{name:'Register',exact:true}).click()
  await expect(page.getByLabel('Verification token')).not.toHaveValue('')
  await page.getByRole('button',{name:'Verify email',exact:true}).click()
  await page.getByLabel('Email',{exact:true}).fill(`${identity}@example.com`)
  await page.getByLabel('Password',{exact:true}).fill('QA-only-password-123!')
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('button',{name:'Administration',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Create paper portfolio',exact:true}).click()
  await page.getByLabel('Asset symbol',{exact:true}).fill('BTC')
  await page.getByLabel('Quantity',{exact:true}).fill('1')
  await page.getByLabel('Simulation price (USD)',{exact:true}).fill('100')
  await page.getByRole('button',{name:'Reserve paper trade',exact:true}).click()
  await page.getByRole('button',{name:'Fill paper trade',exact:true}).click()
  await expect(page.getByText('Paper fill recorded. Balances and history updated.')).toBeVisible()
  await page.getByRole('button',{name:'Notifications & alerts',exact:true}).click()
  await expect(page.getByText(/paper buy: 1/)).toBeVisible()
  await page.getByRole('button',{name:'Mark read',exact:true}).click()
  await expect(page.getByText('Inbox · 0 unread')).toBeVisible()
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download CSV',exact:true}).click()
  expect((await download).suggestedFilename()).toMatch(/\.csv$/)
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Sign in to your portfolio'})).toBeVisible()
})
